--------------------------------------------------------
--  Datei erstellt -Montag-Mai-23-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Type ADRESSE_T
--------------------------------------------------------

  CREATE OR REPLACE TYPE "DBST47"."ADRESSE_T" AS OBJECT(
Strasse  VARCHAR2(30),
HNR INTEGER,
PLZ INTEGER,
Ort VARCHAR2(20)) NOT FINAL;

/
--------------------------------------------------------
--  DDL for Type ADRESSE_T2
--------------------------------------------------------

  CREATE OR REPLACE TYPE "DBST47"."ADRESSE_T2" AS OBJECT(
Strasse  VARCHAR2(30),
HNR INTEGER,
PLZ INTEGER,
Ort VARCHAR2(20)) NOT FINAL;

/
--------------------------------------------------------
--  DDL for Type KONTENLISTE
--------------------------------------------------------

  CREATE OR REPLACE TYPE "DBST47"."KONTENLISTE" as table of REF Konto_t;

/
--------------------------------------------------------
--  DDL for Type KONTENLISTE2
--------------------------------------------------------

  CREATE OR REPLACE TYPE "DBST47"."KONTENLISTE2" as table of Konto_t2;
  
/
--------------------------------------------------------
--  DDL for Type KONTO_T
--------------------------------------------------------

  CREATE OR REPLACE TYPE "DBST47"."KONTO_T" AS OBJECT(
KNR INTEGER,
Kontostand  NUMBER(10,2),
Typ INTEGER(1)) NOT FINAL;

/
--------------------------------------------------------
--  DDL for Type KONTO_T2
--------------------------------------------------------

  CREATE OR REPLACE TYPE "DBST47"."KONTO_T2" AS OBJECT(
KNR INTEGER,
Kontostand  NUMBER(10,2),
Typ INTEGER(1),
Kunden2 Kundenliste2) NOT FINAL;

/
--------------------------------------------------------
--  DDL for Type KUNDENLISTE2
--------------------------------------------------------

  CREATE OR REPLACE TYPE "DBST47"."KUNDENLISTE2" as table of REF PERSON_t2;
  
/
--------------------------------------------------------
--  DDL for Type PERSON_T
--------------------------------------------------------

  CREATE OR REPLACE TYPE "DBST47"."PERSON_T" AS OBJECT(
Kd_NR INTEGER,
Nachname  VARCHAR2(20),
Vorname   VARCHAR2(20),
Adresse REF  Adresse_t,
Status  INTEGER(1),
Konten  Kontenliste) NOT FINAL;

/
--------------------------------------------------------
--  DDL for Type PERSON_T2
--------------------------------------------------------

  CREATE OR REPLACE TYPE "DBST47"."PERSON_T2" AS OBJECT(
Kd_NR INTEGER,
Nachname  VARCHAR2(20),
Vorname   VARCHAR2(20),
Adresse REF  Adresse_t2,
Status  INTEGER(1)) NOT FINAL;

/
--------------------------------------------------------
--  DDL for Type ZWEIGSTELLE_T
--------------------------------------------------------

  CREATE OR REPLACE TYPE "DBST47"."ZWEIGSTELLE_T" AS OBJECT(
ZName VARCHAR2(20),
Adresse REF Adresse_t,
Leiter   Integer,
Konten  Kontenliste) NOT FINAL;

/
--------------------------------------------------------
--  DDL for Type ZWEIGSTELLE_T2
--------------------------------------------------------

  CREATE OR REPLACE TYPE "DBST47"."ZWEIGSTELLE_T2" AS OBJECT(
ZName VARCHAR2(20),
Adresse2 REF Adresse_t2,
Leiter   Integer,
Konten2  Kontenliste2) NOT FINAL;

/
--------------------------------------------------------
--  DDL for Table ADRESSEN
--------------------------------------------------------

  CREATE TABLE "DBST47"."ADRESSEN" OF "DBST47"."ADRESSE_T" 
 OIDINDEX  ( PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ) 
 PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ADRESSEN2
--------------------------------------------------------

  CREATE TABLE "DBST47"."ADRESSEN2" OF "DBST47"."ADRESSE_T2" 
 OIDINDEX  ( PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ) 
 PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table KONTEN
--------------------------------------------------------

  CREATE TABLE "DBST47"."KONTEN" OF "DBST47"."KONTO_T" 
 OIDINDEX  ( PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ) 
 PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
-- Wiedergabe von TABLE DDL für Objekt DBST47.KONTEN_KD nicht möglich, da DBMS_METADATA internen Generator versucht.
CREATE TABLE KONTEN_KD 
(
 ) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS
-- Wiedergabe von TABLE DDL für Objekt DBST47.KONTEN_ZWEIGST nicht möglich, da DBMS_METADATA internen Generator versucht.
CREATE TABLE KONTEN_ZWEIGST 
(
 ) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS
-- Wiedergabe von TABLE DDL für Objekt DBST47.KONTEN_ZWEIGST2 nicht möglich, da DBMS_METADATA internen Generator versucht.
CREATE TABLE KONTEN_ZWEIGST2 
(
 ) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESSCREATE UNIQUE INDEX SYS_C00159562 ON KONTEN_ZWEIGST2 (KUNDEN2 ASC) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL
--------------------------------------------------------
--  DDL for Table KUNDEN
--------------------------------------------------------

  CREATE TABLE "DBST47"."KUNDEN" OF "DBST47"."PERSON_T" 
 OIDINDEX  ( PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ) 
 PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" 
 NESTED TABLE "KONTEN" STORE AS "KONTEN_KD"
 (PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ) RETURN AS VALUE;
-- Wiedergabe von TABLE DDL für Objekt DBST47.KUNDEN_ZWEIGST2 nicht möglich, da DBMS_METADATA internen Generator versucht.
CREATE TABLE KUNDEN_ZWEIGST2 
(
 ) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS
--------------------------------------------------------
--  DDL for Table KUNDEN2
--------------------------------------------------------

  CREATE TABLE "DBST47"."KUNDEN2" OF "DBST47"."PERSON_T2" 
 OIDINDEX  ( PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ) 
 PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ZWEIGSTELLEN
--------------------------------------------------------

  CREATE TABLE "DBST47"."ZWEIGSTELLEN" OF "DBST47"."ZWEIGSTELLE_T" 
 OIDINDEX  ( PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ) 
 PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" 
 NESTED TABLE "KONTEN" STORE AS "KONTEN_ZWEIGST"
 (PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ) RETURN AS VALUE;
--------------------------------------------------------
--  DDL for Table ZWEIGSTELLEN2
--------------------------------------------------------

  CREATE TABLE "DBST47"."ZWEIGSTELLEN2" OF "DBST47"."ZWEIGSTELLE_T2" 
 OIDINDEX  ( PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ) 
 PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" 
 NESTED TABLE "KONTEN2" STORE AS "KONTEN_ZWEIGST2"
 (PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" 
 NESTED TABLE "KUNDEN2" STORE AS "KUNDEN_ZWEIGST2"
 (PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ) RETURN AS VALUE) RETURN AS VALUE;
REM INSERTING into DBST47.ADRESSEN
SET DEFINE OFF;
Insert into DBST47.ADRESSEN (STRASSE,HNR,PLZ,ORT) values ('Simseestr.','3','80800','Musterhausen');
Insert into DBST47.ADRESSEN (STRASSE,HNR,PLZ,ORT) values ('Hochstr.','1','80000','Münchhausen');
Insert into DBST47.ADRESSEN (STRASSE,HNR,PLZ,ORT) values ('Eschenweg','12','80335','München');
Insert into DBST47.ADRESSEN (STRASSE,HNR,PLZ,ORT) values ('Münchnerstr.','33','80801','München');
Insert into DBST47.ADRESSEN (STRASSE,HNR,PLZ,ORT) values ('Schellingstr.','42','53620','Hasenbüttel');
REM INSERTING into DBST47.ADRESSEN2
SET DEFINE OFF;
Insert into DBST47.ADRESSEN2 (STRASSE,HNR,PLZ,ORT) values ('Simseestr.','3','80800','Musterhausen');
Insert into DBST47.ADRESSEN2 (STRASSE,HNR,PLZ,ORT) values ('Hochstr.','1','80000','Münchhausen');
Insert into DBST47.ADRESSEN2 (STRASSE,HNR,PLZ,ORT) values ('Eschenweg','12','80335','München');
Insert into DBST47.ADRESSEN2 (STRASSE,HNR,PLZ,ORT) values ('Münchnerstr.','33','80801','München');
Insert into DBST47.ADRESSEN2 (STRASSE,HNR,PLZ,ORT) values ('Schellingstr.','42','53620','Hasenbüttel');
REM INSERTING into DBST47.KONTEN
SET DEFINE OFF;
Insert into DBST47.KONTEN (KNR,KONTOSTAND,TYP) values ('120768','234,56','0');
Insert into DBST47.KONTEN (KNR,KONTOSTAND,TYP) values ('348973','12567,56','1');
Insert into DBST47.KONTEN (KNR,KONTOSTAND,TYP) values ('678453','-456,78','1');
Insert into DBST47.KONTEN (KNR,KONTOSTAND,TYP) values ('987654','789,65','1');
Insert into DBST47.KONTEN (KNR,KONTOSTAND,TYP) values ('745363','-23,67','0');
REM INSERTING into DBST47.KUNDEN
SET DEFINE OFF;
Insert into DBST47.KUNDEN (KD_NR,NACHNAME,VORNAME,ADRESSE,STATUS,KONTEN) values ('2345','Fach','Hans','DBST47.ADRESSE_T(''Münchnerstr.'',33,80801,''München'')','0',DBST47.KONTENLISTE(DBST47.KONTO_T(120768,234.56,0),DBST47.KONTO_T(348973,12567.56,1)));
Insert into DBST47.KUNDEN (KD_NR,NACHNAME,VORNAME,ADRESSE,STATUS,KONTEN) values ('7654','Meier','Bernd','DBST47.ADRESSE_T(''Eschenweg'',12,80335,''München'')','1',DBST47.KONTENLISTE(DBST47.KONTO_T(987654,789.65,1)));
Insert into DBST47.KUNDEN (KD_NR,NACHNAME,VORNAME,ADRESSE,STATUS,KONTEN) values ('8764','Wiesner','Jan','DBST47.ADRESSE_T(''Schellingstr.'',42,53620,''Hasenbüttel'')','1',DBST47.KONTENLISTE(DBST47.KONTO_T(348973,12567.56,1),DBST47.KONTO_T(678453,-456.78,1),DBST47.KONTO_T(745363,-23.67,0)));
REM INSERTING into DBST47.KUNDEN2
SET DEFINE OFF;
Insert into DBST47.KUNDEN2 (KD_NR,NACHNAME,VORNAME,ADRESSE,STATUS) values ('2345','Fach','Hans','DBST47.ADRESSE_T2(''Münchnerstr.'',33,80801,''München'')','0');
Insert into DBST47.KUNDEN2 (KD_NR,NACHNAME,VORNAME,ADRESSE,STATUS) values ('7654','Meier','Bernd','DBST47.ADRESSE_T2(''Eschenweg'',12,80335,''München'')','1');
Insert into DBST47.KUNDEN2 (KD_NR,NACHNAME,VORNAME,ADRESSE,STATUS) values ('8764','Wiesner','Jan','DBST47.ADRESSE_T2(''Schellingstr.'',42,53620,''Hasenbüttel'')','0');
REM INSERTING into DBST47.ZWEIGSTELLEN
SET DEFINE OFF;
Insert into DBST47.ZWEIGSTELLEN (ZNAME,ADRESSE,LEITER,KONTEN) values ('Bachdorf','DBST47.ADRESSE_T(''Hochstr.'',1,80000,''Münchhausen'')','1768',DBST47.KONTENLISTE(DBST47.KONTO_T(120768,234.56,0),DBST47.KONTO_T(348973,12567.56,1),DBST47.KONTO_T(678453,-456.78,1)));
Insert into DBST47.ZWEIGSTELLEN (ZNAME,ADRESSE,LEITER,KONTEN) values ('Riedering','DBST47.ADRESSE_T(''Simseestr.'',3,80800,''Musterhausen'')','9823',DBST47.KONTENLISTE(DBST47.KONTO_T(987654,789.65,1),DBST47.KONTO_T(745363,-23.67,0)));
REM INSERTING into DBST47.ZWEIGSTELLEN2
SET DEFINE OFF;
Insert into DBST47.ZWEIGSTELLEN2 (ZNAME,ADRESSE2,LEITER,KONTEN2) values ('Bachdorf','DBST47.ADRESSE_T2(''Hochstr.'',1,80000,''Münchhausen'')','1768',DBST47.KONTENLISTE2(DBST47.KONTO_T2(120768,234.56,0,DBST47.KUNDENLISTE2(oracle.sql.REF@2c87490d)),DBST47.KONTO_T2(348973,12567.56,1,DBST47.KUNDENLISTE2(oracle.sql.REF@2c87490d,oracle.sql.REF@f37e437c)),DBST47.KONTO_T2(678453,-456.78,1,DBST47.KUNDENLISTE2(oracle.sql.REF@f37e437c))));
Insert into DBST47.ZWEIGSTELLEN2 (ZNAME,ADRESSE2,LEITER,KONTEN2) values ('Riedering','DBST47.ADRESSE_T2(''Simseestr.'',3,80800,''Musterhausen'')','9823',DBST47.KONTENLISTE2(DBST47.KONTO_T2(987654,789.65,1,DBST47.KUNDENLISTE2(oracle.sql.REF@f37e437c)),DBST47.KONTO_T2(745363,-23.67,0,DBST47.KUNDENLISTE2(oracle.sql.REF@68e341ce))));
--------------------------------------------------------
--  Constraints for Table ZWEIGSTELLEN2
--------------------------------------------------------

  ALTER TABLE "DBST47"."ZWEIGSTELLEN2" ADD UNIQUE ("KONTEN2")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "DBST47"."ZWEIGSTELLEN2" ADD UNIQUE ("SYS_NC_OID$")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ADRESSEN
--------------------------------------------------------

  ALTER TABLE "DBST47"."ADRESSEN" ADD UNIQUE ("SYS_NC_OID$")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ZWEIGSTELLEN
--------------------------------------------------------

  ALTER TABLE "DBST47"."ZWEIGSTELLEN" ADD UNIQUE ("KONTEN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "DBST47"."ZWEIGSTELLEN" ADD UNIQUE ("SYS_NC_OID$")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table KUNDEN
--------------------------------------------------------

  ALTER TABLE "DBST47"."KUNDEN" ADD UNIQUE ("KONTEN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "DBST47"."KUNDEN" ADD UNIQUE ("SYS_NC_OID$")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table KUNDEN2
--------------------------------------------------------

  ALTER TABLE "DBST47"."KUNDEN2" ADD UNIQUE ("SYS_NC_OID$")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ADRESSEN2
--------------------------------------------------------

  ALTER TABLE "DBST47"."ADRESSEN2" ADD UNIQUE ("SYS_NC_OID$")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table KONTEN_ZWEIGST2
--------------------------------------------------------

  ALTER TABLE "DBST47"."KONTEN_ZWEIGST2" ADD UNIQUE ("KUNDEN2")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table KONTEN
--------------------------------------------------------

  ALTER TABLE "DBST47"."KONTEN" ADD UNIQUE ("SYS_NC_OID$")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
