--------------------------------------------------------
--  Datei erstellt -Dienstag-Mai-10-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Type ADRESSE_T
--------------------------------------------------------

  CREATE OR REPLACE TYPE "DBST47"."ADRESSE_T" AS OBJECT(
Strasse  VARCHAR2(30),
HNR INTEGER,
PLZ INTEGER,
Ort VARCHAR2(20)) NOT FINAL;

/
--------------------------------------------------------
--  DDL for Type KONTENLISTE
--------------------------------------------------------

  CREATE OR REPLACE TYPE "DBST47"."KONTENLISTE" as table of REF Konto_t;

/
--------------------------------------------------------
--  DDL for Type KONTO_T
--------------------------------------------------------

  CREATE OR REPLACE TYPE "DBST47"."KONTO_T" AS OBJECT(
KNR INTEGER,
Kontostand  NUMBER(10,2),
Typ INTEGER(1)) NOT FINAL;

/
--------------------------------------------------------
--  DDL for Type PERSON_T
--------------------------------------------------------

  CREATE OR REPLACE TYPE "DBST47"."PERSON_T" AS OBJECT(
Kd_NR INTEGER,
Nachname  VARCHAR2(20),
Vorname   VARCHAR2(20),
Adresse REF  Adresse_t,
Status  INTEGER(1),
Konten  Kontenliste) NOT FINAL;

/
--------------------------------------------------------
--  DDL for Type ZWEIGSTELLE_T
--------------------------------------------------------

  CREATE OR REPLACE TYPE "DBST47"."ZWEIGSTELLE_T" AS OBJECT(
ZName VARCHAR(20),
Adresse  REF Adresse_t,
Leiter    INTEGER,
Konten    Kontenliste) NOT FINAL;

/
--------------------------------------------------------
--  DDL for Table ADRESSEN
--------------------------------------------------------

  CREATE TABLE "DBST47"."ADRESSEN" OF "DBST47"."ADRESSE_T" 
 OIDINDEX  ( PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ) 
 PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table KONTEN
--------------------------------------------------------

  CREATE TABLE "DBST47"."KONTEN" OF "DBST47"."KONTO_T" 
 OIDINDEX  ( PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ) 
 PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
-- Wiedergabe von TABLE DDL für Objekt DBST47.KONTEN_KD nicht möglich, da DBMS_METADATA internen Generator versucht.
CREATE TABLE KONTEN_KD 
(
 ) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS
-- Wiedergabe von TABLE DDL für Objekt DBST47.KONTEN_ZWEIGST nicht möglich, da DBMS_METADATA internen Generator versucht.
CREATE TABLE KONTEN_ZWEIGST 
(
 ) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS
--------------------------------------------------------
--  DDL for Table KUNDEN
--------------------------------------------------------

  CREATE TABLE "DBST47"."KUNDEN" OF "DBST47"."PERSON_T" 
 OIDINDEX  ( PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ) 
 PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" 
 NESTED TABLE "KONTEN" STORE AS "KONTEN_KD"
 (PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ) RETURN AS VALUE;
--------------------------------------------------------
--  DDL for Table ZWEIGSTELLEN
--------------------------------------------------------

  CREATE TABLE "DBST47"."ZWEIGSTELLEN" OF "DBST47"."ZWEIGSTELLE_T" 
 OIDINDEX  ( PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ) 
 PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" 
 NESTED TABLE "KONTEN" STORE AS "KONTEN_ZWEIGST"
 (PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ) RETURN AS VALUE;
REM INSERTING into DBST47.ADRESSEN
SET DEFINE OFF;
Insert into DBST47.ADRESSEN (STRASSE,HNR,PLZ,ORT) values ('Simseestr.','3','80800','Musterhausen');
Insert into DBST47.ADRESSEN (STRASSE,HNR,PLZ,ORT) values ('Hochstr.','1','80000','Münchhausen');
Insert into DBST47.ADRESSEN (STRASSE,HNR,PLZ,ORT) values ('Münchnerstr.','33','80801','München');
Insert into DBST47.ADRESSEN (STRASSE,HNR,PLZ,ORT) values ('Schellingstr.','42','5362','Hasenbüttel');
REM INSERTING into DBST47.KONTEN
SET DEFINE OFF;
Insert into DBST47.KONTEN (KNR,KONTOSTAND,TYP) values ('120768','234,56','0');
Insert into DBST47.KONTEN (KNR,KONTOSTAND,TYP) values ('348973','12567,56','1');
Insert into DBST47.KONTEN (KNR,KONTOSTAND,TYP) values ('678453','-456,78','1');
Insert into DBST47.KONTEN (KNR,KONTOSTAND,TYP) values ('987654','789,65','1');
Insert into DBST47.KONTEN (KNR,KONTOSTAND,TYP) values ('745363','-23,67','0');
REM INSERTING into DBST47.KUNDEN
SET DEFINE OFF;
REM INSERTING into DBST47.ZWEIGSTELLEN
SET DEFINE OFF;
--------------------------------------------------------
--  Constraints for Table KUNDEN
--------------------------------------------------------

  ALTER TABLE "DBST47"."KUNDEN" ADD UNIQUE ("KONTEN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "DBST47"."KUNDEN" ADD UNIQUE ("SYS_NC_OID$")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ADRESSEN
--------------------------------------------------------

  ALTER TABLE "DBST47"."ADRESSEN" ADD UNIQUE ("SYS_NC_OID$")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table KONTEN
--------------------------------------------------------

  ALTER TABLE "DBST47"."KONTEN" ADD UNIQUE ("SYS_NC_OID$")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ZWEIGSTELLEN
--------------------------------------------------------

  ALTER TABLE "DBST47"."ZWEIGSTELLEN" ADD UNIQUE ("KONTEN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "DBST47"."ZWEIGSTELLEN" ADD UNIQUE ("SYS_NC_OID$")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
